[[filters]]
type = "lowpass"
q = 1
frequence = 100

[[filters]]
type = "lowpass"
q = 1
frequence = 100

[[filters]]
type = "lowpass"
q = 1
frequence = 100

[[filters]]
type = "lowpass"
q = 1
frequence = 100